-- Online invoices for Business Web Center.
-- Run after schema.sql and 002_signup_workflow.sql.

begin;

create table if not exists public.invoices (
  id uuid primary key default gen_random_uuid(),
  business_id uuid not null references public.businesses(id) on delete cascade,
  invoice_number bigint generated by default as identity unique,
  client_name text not null,
  contact_number text not null,
  client_address text not null,
  client_email text,
  vehicle_make text not null,
  vehicle_year_model text not null,
  vehicle_color text not null,
  plate_number text not null,
  invoice_date date not null,
  release_date date,
  assigned_admin text not null,
  payment_method text not null,
  client_source text not null,
  total_amount numeric(14,2) not null default 0 check (total_amount >= 0),
  amount_paid numeric(14,2) not null default 0 check (amount_paid >= 0),
  status text not null default 'Pending'
    check (status in ('Pending', 'Partially paid', 'Paid')),
  created_by uuid not null references auth.users(id) on delete restrict,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.invoice_services (
  id uuid primary key default gen_random_uuid(),
  invoice_id uuid not null references public.invoices(id) on delete cascade,
  service_name text not null,
  service_detail text,
  amount numeric(14,2) not null check (amount >= 0),
  created_at timestamptz not null default now()
);

create table if not exists public.invoice_parts (
  id uuid primary key default gen_random_uuid(),
  invoice_id uuid not null references public.invoices(id) on delete cascade,
  part_name text not null,
  quantity numeric(12,2) not null check (quantity > 0),
  unit_price numeric(14,2) not null check (unit_price >= 0),
  created_at timestamptz not null default now()
);

create index if not exists invoices_business_date_idx on public.invoices (business_id, invoice_date desc);
create index if not exists invoice_services_invoice_idx on public.invoice_services (invoice_id);
create index if not exists invoice_parts_invoice_idx on public.invoice_parts (invoice_id);

drop trigger if exists set_invoices_updated_at on public.invoices;
create trigger set_invoices_updated_at
before update on public.invoices
for each row execute procedure public.set_updated_at();

alter table public.invoices enable row level security;
alter table public.invoice_services enable row level security;
alter table public.invoice_parts enable row level security;

drop policy if exists invoices_read on public.invoices;
create policy invoices_read on public.invoices
for select to authenticated
using (public.is_platform_admin() or public.is_business_member(business_id));

drop policy if exists invoices_insert on public.invoices;
create policy invoices_insert on public.invoices
for insert to authenticated
with check (
  (public.is_platform_admin() or public.is_business_manager(business_id))
  and created_by = auth.uid()
);

drop policy if exists invoices_update on public.invoices;
create policy invoices_update on public.invoices
for update to authenticated
using (public.is_platform_admin() or public.is_business_manager(business_id))
with check (public.is_platform_admin() or public.is_business_manager(business_id));

drop policy if exists invoices_delete on public.invoices;
create policy invoices_delete on public.invoices
for delete to authenticated
using (public.is_platform_admin() or public.is_business_manager(business_id));

drop policy if exists invoice_services_read on public.invoice_services;
create policy invoice_services_read on public.invoice_services
for select to authenticated
using (exists (select 1 from public.invoices i where i.id = invoice_id and (public.is_platform_admin() or public.is_business_member(i.business_id))));

drop policy if exists invoice_services_manage on public.invoice_services;
create policy invoice_services_manage on public.invoice_services
for all to authenticated
using (exists (select 1 from public.invoices i where i.id = invoice_id and (public.is_platform_admin() or public.is_business_manager(i.business_id))))
with check (exists (select 1 from public.invoices i where i.id = invoice_id and (public.is_platform_admin() or public.is_business_manager(i.business_id))));

drop policy if exists invoice_parts_read on public.invoice_parts;
create policy invoice_parts_read on public.invoice_parts
for select to authenticated
using (exists (select 1 from public.invoices i where i.id = invoice_id and (public.is_platform_admin() or public.is_business_member(i.business_id))));

drop policy if exists invoice_parts_manage on public.invoice_parts;
create policy invoice_parts_manage on public.invoice_parts
for all to authenticated
using (exists (select 1 from public.invoices i where i.id = invoice_id and (public.is_platform_admin() or public.is_business_manager(i.business_id))))
with check (exists (select 1 from public.invoices i where i.id = invoice_id and (public.is_platform_admin() or public.is_business_manager(i.business_id))));

commit;
