-- Delete an invoice and every CIB movement generated by that invoice as one
-- transaction. A remitted cash collection must be corrected, not deleted.

begin;

create or replace function public.delete_invoice_with_linked_cash(
  p_invoice_id uuid,
  p_branch_id uuid
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_invoice public.invoices%rowtype;
  v_cash_deleted integer := 0;
begin
  select * into v_invoice
  from public.invoices
  where id = p_invoice_id
    and branch_id = p_branch_id
  for update;

  if not found then
    raise exception 'Invoice was not found in the selected branch.';
  end if;

  if not public.can_manage_invoice_branch(v_invoice.business_id, p_branch_id) then
    raise exception 'You do not have permission to delete invoices in this branch.';
  end if;

  if exists (
    select 1
    from public.cash_collections collection
    where collection.invoice_id = v_invoice.id
      and collection.status = 'Remitted'
  ) then
    raise exception 'This invoice has already been remitted. Record a correcting transaction instead of deleting it.';
  end if;

  -- Remove both the older one-record format and the current per-payment format.
  delete from public.cash_transactions
  where business_id = v_invoice.business_id
    and branch_id = p_branch_id
    and (
      source_key = 'invoice-cash:' || v_invoice.id::text
      or source_key like 'invoice-payment-cash:' || v_invoice.id::text || ':%'
    );
  get diagnostics v_cash_deleted = row_count;

  delete from public.service_repair_orders
  where business_id = v_invoice.business_id
    and branch_id = p_branch_id
    and invoice_id = v_invoice.id;

  delete from public.invoices
  where id = v_invoice.id
    and business_id = v_invoice.business_id
    and branch_id = p_branch_id;

  return jsonb_build_object('ok', true, 'cash_records_deleted', v_cash_deleted);
end;
$$;

grant execute on function public.delete_invoice_with_linked_cash(uuid, uuid) to authenticated;

commit;
