-- Keep CIB aligned with dated invoice payments, not the invoice total.
-- This removes only CIB rows generated by the specified invoice and rebuilds
-- them from its payment history in one transaction.

begin;

create or replace function public.sync_invoice_payment_cash(
  p_invoice_id uuid,
  p_branch_id uuid
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_invoice public.invoices%rowtype;
  v_rows integer := 0;
begin
  select * into v_invoice
  from public.invoices
  where id = p_invoice_id
    and branch_id = p_branch_id
  for update;

  if not found then
    raise exception 'Invoice was not found in the selected branch.';
  end if;

  if not public.can_manage_invoice_branch(v_invoice.business_id, p_branch_id) then
    raise exception 'You do not have permission to update invoice payments in this branch.';
  end if;

  delete from public.cash_transactions
  where business_id = v_invoice.business_id
    and branch_id = p_branch_id
    and (
      source_key = 'invoice-cash:' || v_invoice.id::text
      or source_key like 'invoice-payment-cash:' || v_invoice.id::text || ':%'
    );

  insert into public.cash_transactions (
    business_id, branch_id, cash_account, direction, amount, transaction_date,
    source_key, reference_number, notes, created_by
  )
  select
    v_invoice.business_id,
    p_branch_id,
    'CIB',
    'In',
    payment.amount,
    coalesce(payment.payment_date, v_invoice.invoice_date, current_date),
    'invoice-payment-cash:' || v_invoice.id::text || ':' || payment.id::text,
    'INV-' || lpad(v_invoice.invoice_number::text, 5, '0'),
    'Cash payment for invoice - ' || coalesce(v_invoice.client_name, 'Client'),
    coalesce(payment.created_by, auth.uid())
  from public.invoice_payments payment
  where payment.invoice_id = v_invoice.id
    and payment.business_id = v_invoice.business_id
    and payment.branch_id = p_branch_id
    and lower(trim(coalesce(payment.payment_method, ''))) = 'cash';
  get diagnostics v_rows = row_count;

  return jsonb_build_object('ok', true, 'cash_records_synced', v_rows);
end;
$$;

grant execute on function public.sync_invoice_payment_cash(uuid, uuid) to authenticated;

commit;
