/* Keeps the Customize Page, printable documents, and every team device on one brand profile. */
(function(){
  var config=window.BUSINESS_WEB_CENTER_SUPABASE||{},db=null;
  var defaults={header:{type:'Service business management',company:'Your Business Name',description:'Manage invoices, sales, expenses, customer records, quotations, and payroll in one place.',branch:'Your Branch'},theme:{accent:'#ff5219',header:'#080808',background:'#f8f5f3',text:'#16100d',soft:'#fff0e9'},contact:{address:'',phone:'',email:''},logo:''};
  function parse(key,fallback){try{return JSON.parse(localStorage.getItem(key)||'null')||fallback}catch(e){return fallback}}
  function ready(){if(db)return Promise.resolve(true);if(!window.supabase||!config.url||!config.publishableKey)return Promise.resolve(false);db=window.businessSupabase||window.supabase.createClient(config.url,config.publishableKey);return Promise.resolve(true)}
  async function context(){if(!await ready())return null;var session=await db.auth.getSession(),user=session.data&&session.data.session&&session.data.session.user,businessId=localStorage.getItem('bwc-active-business');return user&&businessId?{user:user,businessId:businessId}:null}
  /* A branch is already selected in the header.  If a page loads before the
     header finishes, restore that selection (falling back to MAIN) so a save
     never asks the user to choose a branch again. */
  async function activeBranchId(c){
    var picker=document.getElementById('onlineBranchPicker'),id=(picker&&picker.value)||localStorage.getItem('bwc-active-branch')||'';
    if(id){localStorage.setItem('bwc-active-branch',id);return id}
    if(!c)return '';
    var result=await db.from('branches').select('id,name').eq('business_id',c.businessId).eq('is_active',true).order('created_at');
    if(result.error)return '';
    var rows=result.data||[],main=rows.find(function(row){return row.name==='Main workspace'||row.name==='MAIN'})||rows[0];
    if(main){localStorage.setItem('bwc-active-branch',main.id);return main.id}
    return '';
  }
  /* The master contact is shared by the business.  The legacy print views
     read the other key, which we set to the active branch's print contact. */
  function localProfile(){return {header:Object.assign({},defaults.header,parse('15m-custom-header',{})),theme:Object.assign({},defaults.theme,parse('15m-brand-theme',{})),contact:Object.assign({},defaults.contact,parse('bwc-business-master-contact',parse('15m-business-contact',{}))),logo:localStorage.getItem('15m-custom-logo')||''}}
  function printableContact(contact){var branch=parse('bwc-active-branch-contact',{});return {address:branch.address||contact.address||'',phone:branch.phone||contact.phone||'',email:branch.email||contact.email||''}}
  window.getPrintContact=function(contact){return printableContact(contact||{})}
  function apply(profile){var p={header:Object.assign({},defaults.header,profile.header||{}),theme:Object.assign({},defaults.theme,profile.theme||{}),contact:Object.assign({},defaults.contact,profile.contact||{}),logo:profile.logo||''},root=document.documentElement;root.style.setProperty('--o',p.theme.accent);root.style.setProperty('--s',p.theme.soft);root.style.setProperty('--i',p.theme.text);root.style.setProperty('--p',p.theme.background);var eyebrow=document.querySelector('.brand .eyebrow'),name=document.querySelector('.brand strong'),description=document.querySelector('.brand small'),branch=document.querySelector('.branch strong'),mark=document.querySelector('.mark');if(eyebrow)eyebrow.textContent=p.header.type;if(name)name.textContent=p.header.company;if(description)description.textContent=p.header.description;if(branch)branch.textContent=p.header.branch;if(mark)mark.innerHTML=p.logo?'<img src="'+p.logo+'" alt="Company logo">':'<span class="default-logo">logo</span>';['customBusinessType','customCompanyName','customHeaderDescription','customBranchName'].forEach(function(id){var field=document.getElementById(id),map={customBusinessType:'type',customCompanyName:'company',customHeaderDescription:'description',customBranchName:'branch'};if(field)field.value=p.header[map[id]]||''});var fields={businessAddress:'address',businessPhone:'phone',businessEmail:'email'};Object.keys(fields).forEach(function(id){var field=document.getElementById(id);if(field)field.value=p.contact[fields[id]]||''});var colors={brandAccent:'accent',brandHeader:'header',brandBackground:'background',brandText:'text',brandSoft:'soft'};Object.keys(colors).forEach(function(id){var field=document.getElementById(id);if(field)field.value=p.theme[colors[id]]||defaults.theme[colors[id]]});if(window.__saveBusinessRecoverySnapshot)window.__saveBusinessRecoverySnapshot()}
  async function hydrate(){var c=await context();if(!c)return;var result=await db.from('businesses').select('brand_settings').eq('id',c.businessId).maybeSingle();if(result.error||!result.data)return;var saved=result.data.brand_settings||{},branchId=await activeBranchId(c),branch={};if(branchId){var branchResult=await db.from('branches').select('id,name,address,contact_number,email').eq('id',branchId).eq('business_id',c.businessId).maybeSingle();if(!branchResult.error&&branchResult.data)branch={address:branchResult.data.address||'',phone:branchResult.data.contact_number||'',email:branchResult.data.email||'',name:branchResult.data.name||''}}var profile={header:Object.assign({},defaults.header,saved.header||{}),theme:Object.assign({},defaults.theme,saved.theme||{}),contact:Object.assign({},defaults.contact,saved.contact||{}),logo:saved.logo||''},printContact={address:branch.address||profile.contact.address||'',phone:branch.phone||profile.contact.phone||'',email:branch.email||profile.contact.email||''};localStorage.setItem('15m-custom-header',JSON.stringify(profile.header));localStorage.setItem('15m-brand-theme',JSON.stringify(profile.theme));localStorage.setItem('bwc-business-master-contact',JSON.stringify(profile.contact));localStorage.setItem('bwc-active-branch-contact',JSON.stringify(branch));localStorage.setItem('15m-business-contact',JSON.stringify(printContact));if(profile.logo)localStorage.setItem('15m-custom-logo',profile.logo);else localStorage.removeItem('15m-custom-logo');apply(profile);mountBranchDetails(branch)}
  function mountBranchDetails(branch){var page=document.getElementById('customizePage');if(!page||document.getElementById('branchPrintAddress'))return;var card=document.createElement('div');card.className='card';card.style.marginTop='14px';card.innerHTML='<div class="k">Branch printing details</div><h2>Selected branch address</h2><p class="muted">This address appears on printed invoices, quotations, and repair orders for the selected branch. The company logo and name remain shared.</p><div class="formgrid"><label style="grid-column:1/-1">Branch address<input id="branchPrintAddress" placeholder="Street, barangay, city, province"></label><label>Branch contact number (optional)<input id="branchPrintPhone" placeholder="Use company number if blank"></label><label>Branch email (optional)<input id="branchPrintEmail" type="email" placeholder="Use company email if blank"></label></div><div class="actions" style="margin-top:12px"><button class="primary" type="button" id="saveBranchPrintDetails">Save branch print details</button></div>';page.appendChild(card);document.getElementById('branchPrintAddress').value=branch.address||'';document.getElementById('branchPrintPhone').value=branch.phone||'';document.getElementById('branchPrintEmail').value=branch.email||'';document.getElementById('saveBranchPrintDetails').onclick=async function(){var c=await context(),branchId=await activeBranchId(c);if(!c||!branchId){alert('The current branch is still loading. Please try the save again in a moment.');return}var update={address:document.getElementById('branchPrintAddress').value.trim()||null,contact_number:document.getElementById('branchPrintPhone').value.trim()||null,email:document.getElementById('branchPrintEmail').value.trim()||null};var result=await db.from('branches').update(update).eq('id',branchId).eq('business_id',c.businessId);if(result.error){alert('The branch details could not be saved. '+result.error.message);return}localStorage.setItem('bwc-active-branch-contact',JSON.stringify({address:update.address||'',phone:update.contact_number||'',email:update.email||''}));alert('Branch print details saved.')}}
  async function persist(){var c=await context();if(!c)return;var profile=localProfile();if(profile.logo.length>900000){alert('Please use a smaller logo image (under about 650 KB) so it can sync safely to the whole team.');return}var result=await db.rpc('update_business_brand_settings',{p_business_id:c.businessId,p_settings:profile});if(result.error){alert(result.error.message);return}apply(profile)}
  document.addEventListener('click',function(event){
    if(event.target.closest('[data-t="dashboard"]'))setTimeout(hydrate,80);
    if(event.target.closest('#saveCustomLogo,#deleteCustomLogo,#saveHeaderText,#saveBusinessContact,#saveBrandTheme'))setTimeout(persist,120);
  },true);
  window.addEventListener('load',function(){setTimeout(hydrate,1300)});
  document.addEventListener('bwc:branch-ready',function(){setTimeout(hydrate,120)});
  document.addEventListener('click',function(event){if(event.target.closest('#settingsMenu button[onclick*="openCustomizePage"]'))setTimeout(function(){mountBranchDetails(parse('bwc-active-branch-contact',{}))},180)});
  document.addEventListener('click',function(event){if(!event.target.closest('#saveBranchPrintDetails'))return;setTimeout(function(){var master=localProfile().contact;localStorage.setItem('15m-business-contact',JSON.stringify(printableContact(master)))},160)});
})();
