/* Keeps the Customize Page, printable documents, and every team device on one brand profile. */
(function(){
  var config=window.BUSINESS_WEB_CENTER_SUPABASE||{},db=null;
  var defaults={header:{type:'Service business management',company:'Your Business Name',description:'Manage invoices, sales, expenses, customer records, quotations, and payroll in one place.',branch:'Your Branch'},theme:{accent:'#ff5219',header:'#080808',background:'#f8f5f3',text:'#16100d',soft:'#fff0e9'},contact:{address:'',phone:'',email:''},logo:''};
  function parse(key,fallback){try{return JSON.parse(localStorage.getItem(key)||'null')||fallback}catch(e){return fallback}}
  function ready(){if(db)return Promise.resolve(true);if(!window.supabase||!config.url||!config.publishableKey)return Promise.resolve(false);db=window.businessSupabase||window.supabase.createClient(config.url,config.publishableKey);return Promise.resolve(true)}
  async function context(){if(!await ready())return null;var session=await db.auth.getSession(),user=session.data&&session.data.session&&session.data.session.user,businessId=localStorage.getItem('bwc-active-business');return user&&businessId?{user:user,businessId:businessId}:null}
  function localProfile(){return {header:Object.assign({},defaults.header,parse('15m-custom-header',{})),theme:Object.assign({},defaults.theme,parse('15m-brand-theme',{})),contact:Object.assign({},defaults.contact,parse('15m-business-contact',{})),logo:localStorage.getItem('15m-custom-logo')||''}}
  function apply(profile){var p={header:Object.assign({},defaults.header,profile.header||{}),theme:Object.assign({},defaults.theme,profile.theme||{}),contact:Object.assign({},defaults.contact,profile.contact||{}),logo:profile.logo||''},root=document.documentElement;root.style.setProperty('--o',p.theme.accent);root.style.setProperty('--s',p.theme.soft);root.style.setProperty('--i',p.theme.text);root.style.setProperty('--p',p.theme.background);var eyebrow=document.querySelector('.brand .eyebrow'),name=document.querySelector('.brand strong'),description=document.querySelector('.brand small'),branch=document.querySelector('.branch strong'),mark=document.querySelector('.mark');if(eyebrow)eyebrow.textContent=p.header.type;if(name)name.textContent=p.header.company;if(description)description.textContent=p.header.description;if(branch)branch.textContent=p.header.branch;if(mark)mark.innerHTML=p.logo?'<img src="'+p.logo+'" alt="Company logo">':'<span class="default-logo">logo</span>';['customBusinessType','customCompanyName','customHeaderDescription','customBranchName'].forEach(function(id){var field=document.getElementById(id),map={customBusinessType:'type',customCompanyName:'company',customHeaderDescription:'description',customBranchName:'branch'};if(field)field.value=p.header[map[id]]||''});var fields={businessAddress:'address',businessPhone:'phone',businessEmail:'email'};Object.keys(fields).forEach(function(id){var field=document.getElementById(id);if(field)field.value=p.contact[fields[id]]||''});var colors={brandAccent:'accent',brandHeader:'header',brandBackground:'background',brandText:'text',brandSoft:'soft'};Object.keys(colors).forEach(function(id){var field=document.getElementById(id);if(field)field.value=p.theme[colors[id]]||defaults.theme[colors[id]]});if(window.__saveBusinessRecoverySnapshot)window.__saveBusinessRecoverySnapshot()}
  async function hydrate(){var c=await context();if(!c)return;var result=await db.from('businesses').select('brand_settings').eq('id',c.businessId).maybeSingle();if(result.error||!result.data)return;var saved=result.data.brand_settings||{};if(!Object.keys(saved).length)return;var profile={header:Object.assign({},defaults.header,saved.header||{}),theme:Object.assign({},defaults.theme,saved.theme||{}),contact:Object.assign({},defaults.contact,saved.contact||{}),logo:saved.logo||''};localStorage.setItem('15m-custom-header',JSON.stringify(profile.header));localStorage.setItem('15m-brand-theme',JSON.stringify(profile.theme));localStorage.setItem('15m-business-contact',JSON.stringify(profile.contact));if(profile.logo)localStorage.setItem('15m-custom-logo',profile.logo);else localStorage.removeItem('15m-custom-logo');apply(profile)}
  async function persist(){var c=await context();if(!c)return;var profile=localProfile();if(profile.logo.length>900000){alert('Please use a smaller logo image (under about 650 KB) so it can sync safely to the whole team.');return}var result=await db.rpc('update_business_brand_settings',{p_business_id:c.businessId,p_settings:profile});if(result.error){alert(result.error.message);return}apply(profile)}
  document.addEventListener('click',function(event){
    if(event.target.closest('[data-t="dashboard"]'))setTimeout(hydrate,80);
    if(event.target.closest('#saveCustomLogo,#deleteCustomLogo,#saveHeaderText,#saveBusinessContact,#saveBrandTheme'))setTimeout(persist,120);
  },true);
  window.addEventListener('load',function(){setTimeout(hydrate,1300)});
})();
