/* Shared branch directory and selector. Core records follow the selected branch. */
(function(){
  var config=window.BUSINESS_WEB_CENTER_SUPABASE||{},db=null,activeKey='bwc-active-branch';
  function ready(){if(db)return Promise.resolve(true);if(!window.supabase||!config.url||!config.publishableKey)return Promise.resolve(false);db=window.businessSupabase||window.supabase.createClient(config.url,config.publishableKey);return Promise.resolve(true)}
  async function context(){if(!await ready())return null;var session=await db.auth.getSession(),user=session.data&&session.data.session&&session.data.session.user,businessId=localStorage.getItem('bwc-active-business');return user&&businessId?{user:user,businessId:businessId}:null}
  async function list(){var c=await context();if(!c)return [];var result=await db.from('branches').select('id,name,address,contact_number,email').eq('business_id',c.businessId).eq('is_active',true).order('created_at');return result.error?[]:(result.data||[])}
  async function ensureMain(){var c=await context(),rows=await list();if(!c||rows.length)return rows;var inserted=await db.from('branches').insert({business_id:c.businessId,name:'Main workspace'});if(inserted.error)return rows;return list()}
  function render(rows){var holder=document.querySelector('header .branch');if(!holder)return;var active=localStorage.getItem(activeKey)||'',chosen=rows.find(function(row){return row.id===active})||rows[0];if(chosen)localStorage.setItem(activeKey,chosen.id);holder.innerHTML='<b>BRANCH</b>&nbsp;&nbsp;<select id="onlineBranchPicker" aria-label="Choose branch" style="width:auto;background:transparent;color:#fff;border:0;padding:0;font-weight:bold;max-width:170px">'+rows.map(function(row){return '<option value="'+row.id+'" '+(chosen&&row.id===chosen.id?'selected':'')+'>'+row.name.replace(/[&<>"']/g,'')+'</option>'}).join('')+'</select>';var picker=document.getElementById('onlineBranchPicker');if(picker)picker.onchange=function(){localStorage.setItem(activeKey,picker.value);location.reload()}}
  async function refresh(){var hadActive=!!localStorage.getItem(activeKey),rows=await ensureMain();if(rows.length){render(rows);if(!hadActive)location.reload()}}
  async function create(){var c=await context();if(!c){alert('Please sign in again before creating a branch.');return}var name=prompt('New branch name (for example: Sta. Rosa Branch):');if(name===null)return;name=name.trim();if(!name){alert('Enter a branch name first.');return}var address=prompt('Branch address (optional):','');if(address===null)return;var result=await db.from('branches').insert({business_id:c.businessId,name:name,address:address.trim()||null});if(result.error){alert('The branch could not be created. '+result.error.message);return}var rows=await list(),created=rows.find(function(row){return row.name===name});if(created)localStorage.setItem(activeKey,created.id);location.reload()}
  function bindCreate(){var button=document.getElementById('createBranchMenuButton');if(button)button.onclick=create}
  window.addEventListener('load',function(){setTimeout(function(){refresh();bindCreate();setInterval(bindCreate,1000)},400)});
})();
