/* Online expense adapter. Keeps expense records in Supabase for the active business and branch. */
(function(){
  var db=null,businessId='',userId='',online=false,key='15m-recovery-expenses',editingExpenseId='';
  function message(text){var box=document.getElementById('expenseOnlineStatus');if(!box){box=document.createElement('div');box.id='expenseOnlineStatus';box.className='notice';var view=document.getElementById('expenses');if(view)view.insertBefore(box,view.firstChild)}if(box)box.textContent=text}
  function cache(rows){localStorage.setItem(key,JSON.stringify(rows))}
  function map(row){return {id:'expense-'+row.id,remoteId:row.id,date:row.expense_date,supplier:row.supplier_name||'',receiptNumber:row.receipt_number||'',category:row.category,description:row.description,amount:Number(row.unit_amount||0),quantity:Number(row.quantity||1),payment:row.payment_method||'',reference:row.reference_number||'',remarks:row.remarks||'',branchId:row.branch_id||''}}
  async function resolveBusiness(){
    var session=await db.auth.getSession(),user=session.data&&session.data.session&&session.data.session.user;if(!user)return null;userId=user.id;
    var memberships=await db.from('business_memberships').select('business_id,businesses!inner(id,name,status)').eq('user_id',user.id).eq('status','active');
    var saved=localStorage.getItem('bwc-active-business'),activeRows=(memberships.data||[]).filter(function(row){return row.businesses&&row.businesses.status==='active'}),active=activeRows.find(function(row){return row.business_id===saved})||activeRows[0];if(active){localStorage.setItem('bwc-active-business',active.business_id);localStorage.setItem('bwc-active-business-name',active.businesses.name);return active.business_id}
    var own=await db.from('businesses').select('id,name').eq('created_by',user.id).order('created_at',{ascending:true}).limit(2);if(own.data&&own.data.length===1){localStorage.setItem('bwc-active-business',own.data[0].id);localStorage.setItem('bwc-active-business-name',own.data[0].name);return own.data[0].id}
    return null;
  }
  async function loadRemote(){var query=db.from('expenses').select('*').eq('business_id',businessId),branchId=localStorage.getItem('bwc-active-branch');if(branchId)query=query.eq('branch_id',branchId);var result=await query.order('expense_date',{ascending:false}).order('created_at',{ascending:false});if(result.error){message('Online expenses could not load: '+result.error.message);return}cache((result.data||[]).map(map));syncMissingReceiptCashMovements(result.data||[]);message('Online expense records are active for '+(localStorage.getItem('bwc-active-business-name')||'this business')+'.');document.dispatchEvent(new Event('bwc:expenses-loaded'));setTimeout(decorateExpenseTable,280)}
  function value(id){var el=document.getElementById(id);return el?el.value.trim():''}
  function activeBranch(){return localStorage.getItem('bwc-active-branch')||''}
  function cashAccount(payment){var text=String(payment||'').replace(/\s+/g,' ').trim().toLowerCase();return text==='cib'?'CIB':text==='petty cash'?'Petty Cash':''}
  async function recordCashOut(payment,date,amount,source,reference,notes){var account=cashAccount(payment),branchId=activeBranch();if(!account)return true;if(!branchId||!db||!businessId)return false;var payload={cash_account:account,direction:'Out',amount:Number(amount||0),transaction_date:date||new Date().toISOString().slice(0,10),reference_number:reference||null,notes:notes||null},found=await db.from('cash_transactions').select('id,amount,cash_account,direction').eq('business_id',businessId).eq('branch_id',branchId).eq('source_key',source).limit(1);if(found.error)return false;if(found.data&&found.data.length){var current=found.data[0];if(Number(current.amount||0)!==payload.amount||current.cash_account!==payload.cash_account||current.direction!==payload.direction){var corrected=await db.from('cash_transactions').update(payload).eq('id',current.id).eq('business_id',businessId).eq('branch_id',branchId);if(corrected.error){console.warn('Cash control correction failed',corrected.error.message);return false}document.dispatchEvent(new Event('bwc:cash-updated'))}return true}var result=await db.from('cash_transactions').insert(Object.assign({business_id:businessId,branch_id:branchId,source_key:source,created_by:userId},payload));if(result.error){console.warn('Cash movement could not be saved',result.error.message);return false}document.dispatchEvent(new Event('bwc:cash-updated'));return true}
  async function syncMissingReceiptCashMovements(rows){var branchId=activeBranch();if(!branchId||!rows.length)return;var candidates={},desired={},receipts={};rows.forEach(function(row){var source,amount=Number(row.quantity||1)*Number(row.unit_amount||0),isReceipt=row.remarks==='Manual multi-item receipt entry'&&row.receipt_number;if(isReceipt){source='receipt:'+(row.supplier_name||'')+'|'+row.receipt_number+'|'+row.expense_date;candidates[source]=true;if(!receipts[source])receipts[source]={payment:row.payment_method,date:row.expense_date,total:0,reference:row.receipt_number};receipts[source].total+=amount;return}source='expense:'+row.id;candidates[source]=true;if(cashAccount(row.payment_method))desired[source]={payment:row.payment_method,date:row.expense_date,total:amount,reference:row.reference_number||row.receipt_number,notes:row.description||'Expense payment'}});Object.keys(receipts).forEach(function(source){var item=receipts[source];if(cashAccount(item.payment))desired[source]={payment:item.payment,date:item.date,total:item.total,reference:item.reference,notes:'Receipt expense payment'}});Object.keys(desired).forEach(function(source){candidates[source]=true});var sources=Object.keys(candidates);if(!sources.length)return;var existing=await db.from('cash_transactions').select('id,source_key,amount,cash_account,direction').eq('business_id',businessId).eq('branch_id',branchId).in('source_key',sources);if(existing.error)return;var saved={};(existing.data||[]).forEach(function(row){saved[row.source_key]=row});var missing=[],updates=[],removals=[];sources.forEach(function(source){var item=desired[source],current=saved[source];if(!item){if(current)removals.push(current.id);return}var payload={cash_account:cashAccount(item.payment),direction:'Out',amount:item.total,transaction_date:item.date,reference_number:item.reference||null,notes:item.notes||null};if(!current){missing.push(Object.assign({business_id:businessId,branch_id:branchId,source_key:source,created_by:userId},payload));return}if(Number(current.amount||0)!==Number(item.total)||current.cash_account!==payload.cash_account||current.direction!==payload.direction)updates.push({id:current.id,payload:payload})});var changed=false;if(missing.length){var added=await db.from('cash_transactions').insert(missing);if(added.error){message('Cash records need a refresh: '+added.error.message);return}changed=true}for(var i=0;i<updates.length;i++){var updated=await db.from('cash_transactions').update(updates[i].payload).eq('id',updates[i].id).eq('business_id',businessId).eq('branch_id',branchId);if(updated.error){message('Cash records need a refresh: '+updated.error.message);return}changed=true}if(removals.length){var removed=await db.from('cash_transactions').delete().eq('business_id',businessId).eq('branch_id',branchId).in('id',removals);if(removed.error){message('Cash records need a refresh: '+removed.error.message);return}changed=true}if(changed)document.dispatchEvent(new Event('bwc:cash-updated'))}
  function ensureFields(){var description=document.getElementById('exDescription');if(!description||document.getElementById('exSupplier'))return;var label=description.closest('label');if(!label)return;label.insertAdjacentHTML('beforebegin','<label>Supplier name<input id="exSupplier" placeholder="Optional"></label><label>Receipt number<input id="exReceipt" placeholder="Optional"></label>')}
  function visibleExpenses(){var rows=[];try{rows=JSON.parse(localStorage.getItem(key)||'[]')}catch(e){}var month=(document.getElementById('exMonth')||{}).value||'',year=(document.getElementById('exYear')||{}).value||'';return rows.filter(function(item){var date=new Date(item.date+'T00:00:00');return(!month||date.getMonth()===Number(month))&&(!year||String(date.getFullYear())===String(year))})}
  function isLinked(item){var reference=String(item&&item.reference||''),receipt=String(item&&item.receiptNumber||''),payment=String(item&&item.payment||'');return /^(CIB expense|Petty Cash expense)$/i.test(reference)||/^PAYSLIP/i.test(reference)||/^PAYSLIP/i.test(receipt)||/^(CIB|Petty Cash)$/i.test(payment)}
  function refreshExpenseScreen(){var tab=document.querySelector('[data-t="expenses"]');if(tab)tab.click();setTimeout(decorateExpenseTable,380)}
  function decorateExpenseTable(){var table=document.querySelector('#expenseReceiptTable table,#exTable table');if(!table||table.dataset.onlineExpenseActions)return;var shown=visibleExpenses(),heading=table.querySelector('thead tr');if(!heading)return;var actionHead=document.createElement('th');actionHead.textContent='Action';heading.appendChild(actionHead);Array.prototype.forEach.call(table.querySelectorAll('tbody tr'),function(row,index){var item=shown[index]||{},cell=document.createElement('td');if(!item.remoteId){cell.textContent='-'}else if(isLinked(item)){cell.innerHTML='<span class="muted">Manage in Cash Controls</span>'}else{cell.innerHTML='<div class="actions"><button type="button" class="secondary" data-edit-expense="'+item.remoteId+'">Edit</button><button type="button" class="secondary" data-delete-expense="'+item.remoteId+'">Delete</button></div>'}row.appendChild(cell)});table.dataset.onlineExpenseActions='1'}
  function editorInput(id,label,type){return '<label>'+label+'<input id="'+id+'" type="'+(type||'text')+'"></label>'}
  function renderEditor(item){var old=document.getElementById('expenseOnlineEditor');if(old)old.remove();var table=document.getElementById('expenseReceiptTable');if(!table)return;var categorySelect=document.getElementById('receiptItemCategory'),categories=categorySelect?categorySelect.innerHTML:'<option>Other</option>';var card=document.createElement('div');card.id='expenseOnlineEditor';card.className='card';card.style.marginBottom='14px';card.innerHTML='<div class="k">Edit expense</div><h2>Correct recorded expense</h2><p class="muted">Changes update this expense and Dashboard reporting for the selected branch.</p><div class="formgrid">'+editorInput('expenseEditDate','Date *','date')+editorInput('expenseEditSupplier','Supplier name')+editorInput('expenseEditReceipt','Receipt number')+editorInput('expenseEditDescription','Item / service *')+'<label>Category<select id="expenseEditCategory">'+categories+'</select></label>'+editorInput('expenseEditQuantity','Quantity *','number')+editorInput('expenseEditAmount','Unit amount (PHP) *','number')+'<label>Mode of payment<select id="expenseEditPayment"><option>Cash</option><option>CIB</option><option>Petty Cash</option><option>Authorized Manager</option><option>Bank transfer</option><option>GCash</option><option>Maya</option><option>Check</option></select></label></div><label style="display:block;margin-top:12px">Reference / note<input id="expenseEditReference"></label><div class="actions" style="margin-top:14px"><button type="button" class="primary" data-save-expense-edit="1">Save changes</button><button type="button" class="secondary" data-cancel-expense-edit="1">Cancel</button></div>';table.closest('.card').insertAdjacentElement('beforebegin',card);var set=function(id,val){var el=document.getElementById(id);if(el)el.value=val==null?'':val};set('expenseEditDate',item.date);set('expenseEditSupplier',item.supplier);set('expenseEditReceipt',item.receiptNumber);set('expenseEditDescription',item.description);set('expenseEditCategory',item.category||'Other');set('expenseEditQuantity',item.quantity||1);set('expenseEditAmount',item.amount||0);set('expenseEditPayment',item.payment||'Cash');set('expenseEditReference',item.reference);card.scrollIntoView({behavior:'smooth',block:'nearest'})}
  function startEdit(id){var item=visibleExpenses().find(function(row){return row.remoteId===id});if(!item)return;if(isLinked(item)){alert('This expense was created by Cash Controls or Payroll. Use its original section so linked balances remain correct.');return}editingExpenseId=id;renderEditor(item)}
  function closeEditor(){editingExpenseId='';var card=document.getElementById('expenseOnlineEditor');if(card)card.remove()}
  async function saveEdit(){if(!editingExpenseId)return;var date=value('expenseEditDate'),description=value('expenseEditDescription'),quantity=Number(value('expenseEditQuantity'))||0,amount=Number(value('expenseEditAmount'))||0;if(!date||!description||quantity<1||amount<0){alert('Enter the date, item / service, a quantity of at least 1, and the unit amount.');return}var branchId=localStorage.getItem('bwc-active-branch'),payload={expense_date:date,supplier_name:value('expenseEditSupplier')||null,receipt_number:value('expenseEditReceipt')||null,description:description,category:value('expenseEditCategory')||'Other',quantity:quantity,unit_amount:amount,payment_method:value('expenseEditPayment')||null,reference_number:value('expenseEditReference')||null};message('Saving expense changes securely...');var query=db.from('expenses').update(payload).eq('id',editingExpenseId).eq('business_id',businessId);if(branchId)query=query.eq('branch_id',branchId);var result=await query;if(result.error){alert('The expense could not be updated: '+result.error.message);return}closeEditor();await loadRemote();refreshExpenseScreen();alert('Expense updated. Expenses and Dashboard reporting were refreshed.')}
  async function deleteExpense(id){var item=visibleExpenses().find(function(row){return row.remoteId===id});if(item&&isLinked(item)){alert('This expense was created by Cash Controls or Payroll. Use its original section so linked balances remain correct.');return}var branchId=localStorage.getItem('bwc-active-branch');if(!id||!confirm('Delete this expense entry? This permanently removes it from this branch, Expenses, and Dashboard reporting.'))return;var query=db.from('expenses').delete().eq('id',id).eq('business_id',businessId);if(branchId)query=query.eq('branch_id',branchId);var result=await query;if(result.error){alert('The expense could not be deleted: '+result.error.message);return}await loadRemote();refreshExpenseScreen();alert('Expense deleted. Expenses and Dashboard totals were updated.')}
  function enhanceTable(){var table=document.querySelector('#exTable table');if(!table||table.dataset.receiptColumns)return;var rows=[];try{rows=JSON.parse(localStorage.getItem(key)||'[]')}catch(e){}var month=(document.getElementById('exMonth')||{}).value||'',year=(document.getElementById('exYear')||{}).value||'',shown=rows.filter(function(item){var date=new Date(item.date+'T00:00:00');return(!month||date.getMonth()===Number(month))&&(!year||String(date.getFullYear())===String(year))});var heading=table.querySelector('thead tr');if(!heading)return;var supplierHead=document.createElement('th');supplierHead.textContent='Supplier';var receiptHead=document.createElement('th');receiptHead.textContent='Receipt no.';heading.insertBefore(receiptHead,heading.children[1]);heading.insertBefore(supplierHead,heading.children[1]);Array.prototype.forEach.call(table.querySelectorAll('tbody tr'),function(row,index){var item=shown[index]||{},supplier=document.createElement('td'),receipt=document.createElement('td');supplier.textContent=item.supplier||'-';receipt.textContent=item.receiptNumber||'-';row.insertBefore(receipt,row.children[1]);row.insertBefore(supplier,row.children[1])});table.dataset.receiptColumns='1'}
  async function saveExpense(){
    var description=value('exDescription'),amount=Number(value('exAmount'))||0;if(!description||!amount){alert('Enter an expense description and amount.');return}
    message('Saving expense securely...');
    var payload={business_id:businessId,branch_id:localStorage.getItem('bwc-active-branch'),expense_date:value('exDate'),supplier_name:value('exSupplier')||null,receipt_number:value('exReceipt')||null,category:value('exType'),description:description,quantity:Number(value('exQty'))||1,unit_amount:amount,payment_method:value('exPayment')||null,reference_number:value('exReference')||null,remarks:value('exRemarks')||null,created_by:userId};
    var result=await db.from('expenses').insert(payload).select('id').single();if(result.error){message('Expense was not saved online: '+result.error.message);alert('The expense could not be saved online. Please try again.');return}
    var total=amount*(Number(value('exQty'))||1),cashSaved=await recordCashOut(value('exPayment'),value('exDate'),total,'expense:'+String((result.data&&result.data.id)||Date.now()),value('exReference'),description);await loadRemote();refreshExpenseScreen();alert(cashSaved?'Expense recorded securely and connected to Dashboard reporting.':'Expense recorded, but its CIB / Petty Cash movement needs to be saved again.');
  }
  function money(text){return Number(String(text||'').replace(/[^0-9.-]/g,''))||0}
  function receiptLines(){var rows=document.querySelectorAll('#receiptItems tbody tr'),lines=[];Array.prototype.forEach.call(rows,function(row){var cells=row.querySelectorAll('td');if(cells.length<5)return;var quantity=Number(cells[2].textContent)||0,amount=money(cells[3].textContent);if(cells[0].textContent.trim()&&quantity>0&&amount>0)lines.push({description:cells[0].textContent.trim(),category:cells[1].textContent.trim()||'Other',quantity:quantity,amount:amount})});return lines}
  async function saveReceipt(){
    var supplier=value('receiptSupplier'),receipt=value('receiptNumber'),lines=receiptLines();if(!supplier||!receipt||!lines.length){alert('Enter supplier name, receipt number, and at least one receipt item.');return}
    message('Saving receipt items securely...');
    var date=value('receiptDate'),payment=value('receiptPayment'),payload=lines.map(function(line){return {business_id:businessId,branch_id:localStorage.getItem('bwc-active-branch'),expense_date:date,supplier_name:supplier,receipt_number:receipt,category:line.category,description:line.description,quantity:line.quantity,unit_amount:line.amount,payment_method:payment||null,reference_number:receipt,remarks:'Manual multi-item receipt entry',created_by:userId}});
    var result=await db.from('expenses').insert(payload);if(result.error){message('Receipt items were not saved online: '+result.error.message);alert('The receipt could not be saved online. Please try again.');return}
    var receiptTotal=lines.reduce(function(total,line){return total+line.quantity*line.amount},0),cashSaved=await recordCashOut(payment,date,receiptTotal,'receipt:'+supplier+'|'+receipt+'|'+date,receipt,'Receipt expense payment');await loadRemote();refreshExpenseScreen();alert(cashSaved?'All receipt items were saved securely to Expenses and Dashboard reporting.':'Receipt items were saved, but its CIB / Petty Cash movement needs to be saved again.');
  }
  document.addEventListener('click',function(event){if(event.target.closest('[data-t="expenses"]'))setTimeout(function(){ensureFields();enhanceTable();decorateExpenseTable()},360);var edit=event.target.closest('[data-edit-expense]');if(edit&&online){event.preventDefault();event.stopImmediatePropagation();startEdit(edit.dataset.editExpense);return}var save=event.target.closest('[data-save-expense-edit]');if(save&&online){event.preventDefault();event.stopImmediatePropagation();saveEdit();return}var cancel=event.target.closest('[data-cancel-expense-edit]');if(cancel){event.preventDefault();closeEditor();return}var remove=event.target.closest('[data-delete-expense]');if(remove&&online){event.preventDefault();event.stopImmediatePropagation();deleteExpense(remove.dataset.deleteExpense);return}var receiptSave=event.target.closest('[data-receipt-save]');if(receiptSave&&online){event.preventDefault();event.stopImmediatePropagation();saveReceipt();return}var add=event.target.closest('[data-exp-add]');if(!add||!online)return;event.preventDefault();event.stopImmediatePropagation();saveExpense()},true);
  async function start(){var config=window.BUSINESS_WEB_CENTER_SUPABASE||{};if(!window.supabase||!config.url||!config.publishableKey){setTimeout(start,300);return}db=window.businessSupabase||window.supabase.createClient(config.url,config.publishableKey);businessId=await resolveBusiness();if(!businessId){message('Online expenses are ready, but this account has no selected active business yet.');return}online=true;loadRemote();setTimeout(function(){ensureFields();enhanceTable();decorateExpenseTable()},850)}
  document.addEventListener('bwc:expenses-loaded',function(){setTimeout(decorateExpenseTable,140)});
  document.addEventListener('change',function(event){if(event.target&&['exMonth','exYear'].indexOf(event.target.id)>=0)setTimeout(decorateExpenseTable,120)});
  document.addEventListener('bwc:branch-ready',function(){if(online){closeEditor();loadRemote()}});
  setTimeout(start,650);
})();
