/* Shares Client Feedback and the Owner Feedback inbox for the active business. */
(function(){
  window.__useOnlineFeedback=true;
  var config=window.BUSINESS_WEB_CENTER_SUPABASE||{}, db=null, key='15m-replica-client-feedback';
  function read(){try{return JSON.parse(localStorage.getItem(key)||'[]')}catch(e){return []}}
  function write(items){localStorage.setItem(key,JSON.stringify(items))}
  function esc(value){return String(value||'').replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
  function ready(){if(db)return Promise.resolve(true);if(!window.supabase||!config.url||!config.publishableKey)return Promise.resolve(false);db=window.businessSupabase||window.supabase.createClient(config.url,config.publishableKey);return Promise.resolve(true)}
  async function context(){if(!await ready())return null;var session=await db.auth.getSession(),user=session.data&&session.data.session&&session.data.session.user,businessId=localStorage.getItem('bwc-active-business');return user&&businessId?{user:user,businessId:businessId}:null}
  function mapped(rows){return (rows||[]).map(function(row){return {id:row.id,client:row.client_name||'Anonymous client',rating:row.rating||'',text:row.feedback_text,created:row.created_at}})}
  function feedbackUrl(token){return new URL('feedback.html',location.href).href+'?token='+encodeURIComponent(token)}
  async function publicLink(){var c=await context();if(!c)return null;var found=await db.from('business_feedback_links').select('public_token').eq('business_id',c.businessId).maybeSingle();if(found.data)return found.data.public_token;var created=await db.from('business_feedback_links').insert({business_id:c.businessId}).select('public_token').single();return created.data&&created.data.public_token||null}
  function brand(){var header={company:localStorage.getItem('bwc-active-business-name')||'Your Business Name'},theme={accent:'#ff5219',text:'#16100d'},logo=localStorage.getItem('15m-custom-logo')||'';try{header=Object.assign(header,JSON.parse(localStorage.getItem('15m-custom-header')||'{}'));theme=Object.assign(theme,JSON.parse(localStorage.getItem('15m-brand-theme')||'{}'))}catch(e){}return {company:header.company||'Your Business Name',theme:theme,logo:logo}}
  async function renderFeedback(){var root=document.getElementById('feedback');if(!root)return;var token=await publicLink();if(!token){root.innerHTML='<div class="card"><h2>Client feedback QR</h2><p class="muted">Only the business owner or an admin can create the feedback QR code.</p></div>';return}var link=feedbackUrl(token),qr='https://api.qrserver.com/v1/create-qr-code/?size=260x260&data='+encodeURIComponent(link),items=read(),inbox=items.length?items.map(function(item){return '<div class="notice" style="margin-top:8px"><b>'+esc(item.text)+'</b><br><small>'+esc(item.client||'Anonymous client')+' &middot; Submitted '+esc(item.created?new Date(item.created).toLocaleString():'')+'</small></div>'}).join(''):'<div class="empty">No client feedback has been received yet.</div>';root.innerHTML='<div class="split"><div class="card" style="text-align:center"><div class="k">CLIENT FEEDBACK QR</div><h2>Print or share this feedback code</h2><img src="'+qr+'" alt="Feedback QR code" style="width:220px;height:220px;max-width:100%;margin:14px auto;display:block"><p class="muted">Each business has its own code. Scanning it opens a public feedback form that sends comments only to this business.</p><input id="cfPublicLink" readonly value="'+esc(link)+'" style="width:100%;box-sizing:border-box"><div style="display:flex;gap:8px;margin-top:10px"><button class="secondary" style="flex:1" data-cf-copy>Copy link</button><button class="primary" style="flex:1" data-cf-print>Print QR poster</button></div></div><div class="card"><div class="k">CLIENT FEEDBACK</div><h2>Received feedback</h2><p class="muted">Comments submitted from the QR code appear here automatically.</p>'+inbox+'</div></div>'}
  function printPoster(){var input=document.getElementById('cfPublicLink');if(!input)return;var link=input.value,qr='https://api.qrserver.com/v1/create-qr-code/?size=420x420&data='+encodeURIComponent(link),name=localStorage.getItem('bwc-active-business-name')||'Our business',w=window.open('','_blank');if(!w)return;w.document.write('<title>Feedback QR</title><style>@page{margin:.55in}body{font-family:Arial;text-align:center}img{width:330px;height:330px}h1{font-size:28px}p{font-size:16px}</style><h1>'+esc(name)+'</h1><h2>Share your feedback</h2><img src="'+qr+'"><p>Scan this code to send anonymous feedback.</p>');w.document.close();w.print()}
  function renderOwner(){var root=document.getElementById('owner');if(!root)return;var items=read();root.innerHTML='<div class="heading"><div><div class="k">Private inbox</div><h1>Owner feedback inbox</h1><p class="muted">Every shared client comment appears here for your management team.</p></div></div>'+(items.length?'<div class="card">'+items.map(function(item){return '<div class="notice" style="margin-top:8px"><b>'+esc(item.text)+'</b><br><small>'+esc(item.client||'Anonymous client')+(item.rating?' · '+esc(item.rating)+'/5':'')+' · Submitted '+esc(item.created?new Date(item.created).toLocaleString():'')+'</small></div>'}).join('')+'</div>':'<div class="card empty">No client feedback has been received yet.</div>')}
  async function hydrate(){var c=await context();if(!c)return;var result=await db.from('business_feedback').select('*').eq('business_id',c.businessId).order('created_at',{ascending:false});if(result.error)return;write(mapped(result.data));if(document.getElementById('feedback')&&document.getElementById('feedback').classList.contains('active'))renderFeedback();if(document.getElementById('owner')&&document.getElementById('owner').classList.contains('active'))renderOwner()}
  async function persist(text){var c=await context();if(!c||!text)return;var result=await db.from('business_feedback').insert({business_id:c.businessId,client_name:'Anonymous client',feedback_text:text,source:'client',created_by:c.user.id});if(result.error){alert('Feedback could not be saved online. Please try again.');return}await hydrate();var message=document.getElementById('cfMessage');if(message)message.textContent='Thank you. Your feedback was shared with the business owner.'}
  function printPoster(){var input=document.getElementById('cfPublicLink');if(!input)return;var link=input.value,qr='https://api.qrserver.com/v1/create-qr-code/?size=520x520&data='+encodeURIComponent(link),profile=brand(),logo=profile.logo?'<img class="logo" src="'+esc(profile.logo)+'" alt="Company logo">':'',w=window.open('','_blank');if(!w)return;w.document.open();w.document.write('<!doctype html><html><head><title>Feedback QR</title><style>@page{margin:.55in}body{font-family:Arial,sans-serif;text-align:center;color:'+profile.theme.text+'}.head{border-bottom:3px solid '+profile.theme.accent+';padding:0 0 14px;margin-bottom:22px;display:flex;gap:12px;align-items:center;justify-content:center}.logo{width:52px;height:52px;object-fit:contain}.name{font-size:27px;font-weight:bold}.title{font-size:21px;font-weight:bold;color:'+profile.theme.accent+';margin:14px 0}.qr{width:330px;height:330px;display:block;margin:18px auto}p{font-size:15px}</style></head><body><div class="head">'+logo+'<div class="name">'+esc(profile.company)+'</div></div><div class="title">Share your feedback</div><img id="feedbackQr" class="qr" src="'+qr+'" alt="Feedback QR code"><p>Loading QR code...</p><script>var image=document.getElementById("feedbackQr");image.onload=function(){document.querySelector("p").textContent="Scan this code to send anonymous feedback.";setTimeout(function(){window.print()},150)};image.onerror=function(){document.querySelector("p").textContent="The QR image could not load. Please close this window and try printing again."};</script></body></html>');w.document.close()}
  document.addEventListener('click',function(event){
    if(event.target.closest('[data-t="feedback"], [data-restore-tab="feedback"]'))setTimeout(function(){hydrate();renderFeedback()},60);
    if(event.target.closest('[data-t="owner"], [data-restore-tab="owner"]'))setTimeout(hydrate,60);
    if(event.target.closest('[data-cf-copy]')){var copy=document.getElementById('cfPublicLink');if(copy&&navigator.clipboard)navigator.clipboard.writeText(copy.value);}
    if(event.target.closest('[data-cf-print]'))printPoster();
    if(event.target.closest('[data-cf-submit]')){var input=document.getElementById('cfText'),text=input&&input.value.trim();setTimeout(function(){persist(text)},80)}
  },true);
  function refreshActiveFeedback(){hydrate();if(document.getElementById('feedback')&&document.getElementById('feedback').classList.contains('active'))renderFeedback()}
  window.addEventListener('load',function(){setTimeout(refreshActiveFeedback,250)});
  document.addEventListener('bwc:business-ready',function(){setTimeout(refreshActiveFeedback,80)});
  document.addEventListener('bwc:branch-ready',function(){setTimeout(refreshActiveFeedback,80)});
})();
