/* Makes quotation drafts and quotations shared for the active business. */
(function(){
  var config=window.BUSINESS_WEB_CENTER_SUPABASE||{},db=null,key='15m-replica-quotes';
  function read(){try{return JSON.parse(localStorage.getItem(key)||'[]')}catch(e){return []}}
  function write(items){localStorage.setItem(key,JSON.stringify(items))}
  function ready(){if(db)return Promise.resolve(true);if(!window.supabase||!config.url||!config.publishableKey)return Promise.resolve(false);db=window.businessSupabase||window.supabase.createClient(config.url,config.publishableKey);return Promise.resolve(true)}
  async function context(){if(!await ready())return null;var session=await db.auth.getSession(),user=session.data&&session.data.session&&session.data.session.user,businessId=localStorage.getItem('bwc-active-business');return user&&businessId?{user:user,businessId:businessId}:null}
  function mapQuote(q){var d=q.details||{},lines=(q.quotation_lines||[]).slice().sort(function(a,b){return a.sort_order-b.sort_order}).map(function(x){return {category:x.category,description:x.description,qty:Number(x.quantity),price:Number(x.unit_price)}});return {id:q.id,number:q.quotation_number,status:q.status,client:q.client_name,contact:q.contact_number,address:q.client_address,vehicle:q.vehicle,plate:q.plate_number,date:q.quotation_date,valid:q.valid_until||'',color:d.color||'',vin:d.vin||'',damage:d.damage||'',repair:d.repair||'',deposit:d.deposit||'',notes:d.notes||'',lines:lines,total:Number(q.total_amount)}}
  async function hydrate(){var c=await context();if(!c)return;var result=await db.from('quotations').select('*,quotation_lines(*)').eq('business_id',c.businessId).order('updated_at',{ascending:false});if(result.error)return;write((result.data||[]).map(mapQuote))}
  function currentSaved(){var client=(document.getElementById('qtClient')||{}).value||'',date=(document.getElementById('qtDate')||{}).value||'',vehicle=(document.getElementById('qtVehicle')||{}).value||'',plate=(document.getElementById('qtPlate')||{}).value||'',all=read();return all.find(function(q){return q.client===client&&q.date===date&&q.vehicle===vehicle&&q.plate===plate})||all[0]||null}
  async function persist(){var c=await context(),q=currentSaved();if(!c||!q||!q.lines||!q.lines.length)return;if(!q.client.trim())return;var payload={business_id:c.businessId,quotation_number:q.number,status:q.status==='Draft'?'Draft':'Ready',client_name:q.client,contact_number:q.contact||'',client_address:q.address||'',vehicle:q.vehicle||'',plate_number:q.plate||'',quotation_date:q.date||new Date().toISOString().slice(0,10),valid_until:q.valid||null,total_amount:Number(q.total||0),details:{color:q.color||'',vin:q.vin||'',damage:q.damage||'',repair:q.repair||'',deposit:q.deposit||'',notes:q.notes||''},created_by:c.user.id};var parent=await db.from('quotations').upsert(payload,{onConflict:'business_id,quotation_number'}).select('id').single();if(parent.error){alert('The quotation could not be saved online. '+parent.error.message);return}var removed=await db.from('quotation_lines').delete().eq('quotation_id',parent.data.id);if(removed.error){alert('The quotation could not update its line items.');return}var rows=q.lines.map(function(line,index){return {quotation_id:parent.data.id,category:line.category||'Body & Tinsmith',description:line.description,quantity:Number(line.qty)||1,unit_price:Number(line.price)||0,sort_order:index}});var lines=await db.from('quotation_lines').insert(rows);if(lines.error){alert('The quotation header was saved, but its line items need retrying.');return}var all=read(),index=all.findIndex(function(x){return x.number===q.number});if(index>=0){all[index].id=parent.data.id;write(all)}document.dispatchEvent(new CustomEvent('bwc:quotations-saved'));}
  document.addEventListener('click',function(e){var button=e.target.closest('[data-qt="save-ready"]');if(!button)return;setTimeout(persist,100)},true);
  document.addEventListener('click',function(e){if(e.target.closest('[data-t="quotes"]'))setTimeout(hydrate,20)},true);
  window.addEventListener('load',function(){setTimeout(hydrate,700)});
})();
