/* Quote type fields for vehicle servicing, detailing, and corporate contracts. */
(function(){
  var key='15m-replica-quotes';
  function read(){try{return JSON.parse(localStorage.getItem(key)||'[]')}catch(e){return []}}
  function write(rows){localStorage.setItem(key,JSON.stringify(rows))}
  function value(id){var field=document.getElementById(id);return field?field.value.trim():''}
  function data(){var quoteType=value('qtQuoteType')||'Standard vehicle service',corporate=quoteType==='Corporate maintenance contract';return {quoteType:quoteType,odometer:value('qtOdometer'),concern:value('qtConcern'),recommendations:value('qtRecommendations'),location:value(corporate?'qtServiceLocationCorporate':'qtServiceLocation'),frequency:value(corporate?'qtFrequencyCorporate':'qtFrequency'),detailers:value('qtDetailers'),dutyHours:value('qtDutyHours'),contractStart:value('qtContractStart'),contractEnd:value('qtContractEnd'),billing:value('qtBilling'),terms:value('qtTerms'),exclusions:value('qtExclusions')}}
  function set(id,text){var field=document.getElementById(id);if(field)field.value=text||''}
  function apply(){var type=value('qtQuoteType'),pms=document.getElementById('qtPmsFields'),detail=document.getElementById('qtDetailFields'),corporate=document.getElementById('qtCorporateFields');if(pms)pms.style.display=type==='PMS / Mechanical service'?'grid':'none';if(detail)detail.style.display=type==='Detailing service'?'grid':'none';if(corporate)corporate.style.display=type==='Corporate maintenance contract'?'grid':'none'}
  function mount(){
    var notes=document.getElementById('qtNotes');if(!notes||document.getElementById('qtQuoteType'))return;
    var host=notes.closest('.formgrid');if(!host)return;
    var box=document.createElement('div');box.id='qtQuoteTypePanel';box.style.cssText='grid-column:1/-1;border:1px solid var(--l);border-radius:9px;padding:12px;background:#fffaf8';
    box.innerHTML='<div class="k">Quote type</div><div class="formgrid"><label>Service quotation type<select id="qtQuoteType"><option>Standard vehicle service</option><option>PMS / Mechanical service</option><option>Detailing service</option><option>Corporate maintenance contract</option></select></label></div><div id="qtPmsFields" class="formgrid" style="display:none;margin-top:10px"><label>Odometer reading<input id="qtOdometer" placeholder="e.g., 45,000 km"></label><label>Client concern / diagnosis<input id="qtConcern" placeholder="e.g., Engine vibration"></label><label>Recommended repairs<input id="qtRecommendations" placeholder="Optional recommended work"></label></div><div id="qtDetailFields" class="formgrid" style="display:none;margin-top:10px"><label>Service location<input id="qtServiceLocation" placeholder="e.g., Mall display area"></label><label>Service frequency<select id="qtFrequency"><option value="">Select frequency</option><option>One-time service</option><option>Daily</option><option>Weekly</option><option>Monthly</option></select></label></div><div id="qtCorporateFields" class="formgrid" style="display:none;margin-top:10px"><label>Showroom / mall location<input id="qtServiceLocationCorporate" placeholder="e.g., SM City showroom"></label><label>Service frequency<select id="qtFrequencyCorporate"><option value="">Select frequency</option><option>Daily</option><option>Weekly</option><option>Monthly</option></select></label><label>Number of detailers<input id="qtDetailers" type="number" min="1" placeholder="e.g., 2"></label><label>Duty hours<input id="qtDutyHours" placeholder="e.g., 9 AM–6 PM"></label><label>Contract start<input id="qtContractStart" type="date"></label><label>Contract end<input id="qtContractEnd" type="date"></label><label>Billing schedule<select id="qtBilling"><option value="">Select billing schedule</option><option>Per visit</option><option>Weekly</option><option>Monthly</option></select></label><label>Payment terms<input id="qtTerms" placeholder="e.g., Net 30 days"></label><label style="grid-column:1/-1">Service exclusions<textarea id="qtExclusions" placeholder="Optional exclusions or materials not included"></textarea></label></div><p class="muted" style="margin:10px 0 0">The selected type and its details are saved with this quotation.</p>';
    notes.closest('label').insertAdjacentElement('beforebegin',box);
    box.querySelector('#qtQuoteType').addEventListener('change',apply);apply();
  }
  function selectedQuote(){var client=value('qtClient'),date=value('qtDate'),vehicle=value('qtVehicle'),plate=value('qtPlate');return read().find(function(q){return q.client===client&&q.date===date&&q.vehicle===vehicle&&q.plate===plate})||null}
  function saveLocal(){var quote=selectedQuote();if(!quote)return null;Object.assign(quote,data());var rows=read(),index=rows.findIndex(function(q){return q.id===quote.id});if(index>=0){rows[index]=quote;write(rows)}return quote}
  async function syncOnline(){var quote=saveLocal(),config=window.BUSINESS_WEB_CENTER_SUPABASE||{},db=window.businessSupabase;if(!quote||!db||!config.url)return;var session=await db.auth.getSession(),user=session.data&&session.data.session&&session.data.session.user,business=localStorage.getItem('bwc-active-business'),branch=localStorage.getItem('bwc-active-branch');if(!user||!business||!branch)return;var query=db.from('quotations').select('id,details').eq('business_id',business).eq('branch_id',branch).eq('quotation_number',quote.number).maybeSingle(),found=await query;if(found.error||!found.data)return;var details=Object.assign({},found.data.details||{},data());await db.from('quotations').update({details:details}).eq('id',found.data.id).eq('business_id',business).eq('branch_id',branch)}
  function loadQuote(id){var quote=read().find(function(q){return String(q.id)===String(id)});if(!quote)return;set('qtQuoteType',quote.quoteType||'Standard vehicle service');set('qtOdometer',quote.odometer);set('qtConcern',quote.concern);set('qtRecommendations',quote.recommendations);set('qtServiceLocation',quote.location);set('qtFrequency',quote.frequency);set('qtServiceLocationCorporate',quote.location);set('qtFrequencyCorporate',quote.frequency);set('qtDetailers',quote.detailers);set('qtDutyHours',quote.dutyHours);set('qtContractStart',quote.contractStart);set('qtContractEnd',quote.contractEnd);set('qtBilling',quote.billing);set('qtTerms',quote.terms);set('qtExclusions',quote.exclusions);apply()}
  function mergeServerDetails(){var config=window.BUSINESS_WEB_CENTER_SUPABASE||{},db=window.businessSupabase,business=localStorage.getItem('bwc-active-business'),branch=localStorage.getItem('bwc-active-branch');if(!db||!business||!branch)return;db.from('quotations').select('quotation_number,details').eq('business_id',business).eq('branch_id',branch).then(function(result){if(result.error)return;var rows=read(),changed=false;(result.data||[]).forEach(function(remote){var local=rows.find(function(q){return q.number===remote.quotation_number});if(local&&remote.details){Object.assign(local,{quoteType:remote.details.quoteType||remote.details.quote_type||local.quoteType,odometer:remote.details.odometer||'',concern:remote.details.concern||'',recommendations:remote.details.recommendations||'',location:remote.details.location||'',frequency:remote.details.frequency||'',detailers:remote.details.detailers||'',dutyHours:remote.details.dutyHours||'',contractStart:remote.details.contractStart||'',contractEnd:remote.details.contractEnd||'',billing:remote.details.billing||'',terms:remote.details.terms||'',exclusions:remote.details.exclusions||''});changed=true}});if(changed)write(rows)})}
  document.addEventListener('click',function(event){var nav=event.target.closest('[data-t="quotes"]');if(nav)setTimeout(function(){mount();mergeServerDetails()},100);var open=event.target.closest('[data-qt-edit]');if(open)setTimeout(function(){mount();loadQuote(open.dataset.qtEdit)},80);var save=event.target.closest('[data-qt="save-ready"],[data-qt="save-draft"]');if(save)setTimeout(syncOnline,300)},true);
  document.addEventListener('bwc:quotations-saved',function(){setTimeout(syncOnline,80)});
  window.addEventListener('load',function(){setTimeout(function(){mount();mergeServerDetails()},900)});
})();
