/* Online reporting layer. Dashboard and Sales Report use the same secure
   Invoice and Expense records as the rest of the business workspace. */
(function(){
  var db=null,businessId='',invoices=[],expenses=[],cashRows=[],ready=false,timer=0;
  function peso(value){return 'PHP '+(Number(value||0)).toLocaleString('en-PH',{minimumFractionDigits:2,maximumFractionDigits:2})}
  function number(value){return Number(value||0)||0}
  function period(item,month,year){var date=new Date((item.invoice_date||item.expense_date||item.date)+'T00:00:00');return(!month||date.getMonth()===Number(month))&&(!year||String(date.getFullYear())===String(year))}
  function activeBusiness(){return localStorage.getItem('bwc-active-business')||''}
  function setText(id,value){var el=document.getElementById(id);if(el)el.textContent=value}
  function selected(){return {month:(document.getElementById('dm')||{}).value||'',year:(document.getElementById('dy')||{}).value||''}}
  function cashBalances(rows){var balances={cib:0,petty:0};(rows||[]).forEach(function(row){var account=String(row.cash_account||'').toLowerCase().replace(/\s+/g,'').trim(),key=account==='cib'?'cib':(account==='pettycash'?'petty':'');if(!key)return;var amount=number(row.amount);balances[key]+=String(row.direction||'').toLowerCase()==='out'?-amount:amount});return balances}
  function setCashCard(label,value){var card=[].slice.call(document.querySelectorAll('.muted')).find(function(element){return element.textContent.trim()===label});var metric=card&&card.parentElement?card.parentElement.querySelector('.metric'):null;if(metric)metric.textContent=value}
  function drawCashBalances(){var balances=cashBalances(cashRows);setCashCard('CIB cash in hand',peso(balances.cib));setCashCard('Petty cash remaining',peso(balances.petty))}
  function serviceSales(rows){var mix={};rows.forEach(function(invoice){var total=number(invoice.total_amount),paid=number(invoice.amount_paid),ratio=total?Math.min(1,paid/total):0;(invoice.invoice_services||[]).forEach(function(line){var name=line.service_name||'Service';mix[name]=(mix[name]||0)+number(line.amount)*ratio})});return mix}
  function drawOpexDetails(rows){var dashboard=document.getElementById('dashboard');if(!dashboard)return;var card=document.getElementById('dashboardOpexDetails');if(!card){card=document.createElement('div');card.id='dashboardOpexDetails';card.className='card';card.style.marginTop='14px';dashboard.appendChild(card)}var grouped={};rows.forEach(function(item){var category=item.category||'Other',amount=number(item.quantity)*number(item.unit_amount);grouped[category]=(grouped[category]||0)+amount});var categories=Object.keys(grouped).sort(function(a,b){return grouped[b]-grouped[a]});var summary=categories.length?'<div class="grid" style="margin-top:12px">'+categories.map(function(category){return '<div class="mini"><div class="muted">'+escapeHtml(category)+'</div><div class="metric">'+peso(grouped[category])+'</div></div>'}).join('')+'</div>':'<div class="empty">No operating expenses recorded in the selected period.</div>';var records=rows.length?'<div style="overflow:auto;margin-top:14px"><table><thead><tr><th>Date</th><th>Supplier</th><th>Item / service</th><th>Category</th><th>Qty</th><th>Amount</th><th>Payment</th></tr></thead><tbody>'+rows.map(function(item){var total=number(item.quantity)*number(item.unit_amount);return '<tr><td>'+escapeHtml(item.expense_date)+'</td><td>'+escapeHtml(item.supplier_name||'—')+'</td><td>'+escapeHtml(item.description||'—')+'</td><td>'+escapeHtml(item.category||'Other')+'</td><td>'+number(item.quantity)+'</td><td><b>'+peso(total)+'</b></td><td>'+escapeHtml(item.payment_method||'—')+'</td></tr>'}).join('')+'</tbody></table></div>':'';card.innerHTML='<div class="k">Operating expenses</div><h2>OPEX breakdown and records</h2><p class="muted">These are all non-Cost of Sales expenses for the selected Dashboard month and year. Cost of Sales remains reported separately.</p>'+summary+records}
  function drawDashboard(){if(!ready)return;var current=selected(),list=invoices.filter(function(item){return period(item,current.month,current.year)}),costItems=expenses.filter(function(item){return period(item,current.month,current.year)}),paid=list.filter(function(item){return number(item.amount_paid)>0}),sales=paid.reduce(function(sum,item){return sum+number(item.amount_paid)},0),unpaid=list.reduce(function(sum,item){return sum+Math.max(0,number(item.total_amount)-number(item.amount_paid))},0),cost=costItems.filter(function(item){return item.category==='Cost of Sales'}).reduce(function(sum,item){return sum+number(item.quantity)*number(item.unit_amount)},0),opexEntries=costItems.filter(function(item){return item.category!=='Cost of Sales'}),opex=opexEntries.reduce(function(sum,item){return sum+number(item.quantity)*number(item.unit_amount)},0),gross=sales-cost,net=gross-opex,mix=serviceSales(paid);
    setText('paidSales',peso(sales));setText('paidCount',paid.length+' invoice'+(paid.length===1?'':'s')+' with payment');setText('unpaid',peso(unpaid));setText('profit',peso(net));setText('gross',peso(gross));setText('net',peso(net));
    var expenseCard=document.querySelector('#dashboard .grid .card:nth-child(2) .metric');if(expenseCard)expenseCard.textContent=peso(opex);
    var expenseNote=document.querySelector('#dashboard .grid .card:nth-child(2) .muted:last-child');if(expenseNote)expenseNote.textContent=costItems.filter(function(item){return item.category!=='Cost of Sales'}).length+' OPEX entries';
    var serviceRows=Object.keys(mix).map(function(name){return '<div class="line"><span>'+escapeHtml(name)+'</span><b>'+peso(mix[name])+'</b></div>'}).join('')||'<div class="empty">No invoice payments received yet.</div>';
    var dashboardServices=document.getElementById('dashboardServices'),mixBox=document.getElementById('mix');if(dashboardServices)dashboardServices.innerHTML=serviceRows;if(mixBox)mixBox.innerHTML=serviceRows;
    var summary=document.getElementById('accountingSummaryCard');if(summary)summary.innerHTML='<div class="k">Accounting summary</div><h2>Sales, cost of sales, and OPEX</h2><div class="pl"><div><div class="k">Cash received</div><div class="metric">'+peso(sales)+'</div></div><div><div class="k">Cost of sales</div><div class="metric">'+peso(cost)+'</div><div class="muted">Gross profit: '+peso(gross)+'</div></div><div><div class="k">Total OPEX</div><div class="metric">'+peso(opex)+'</div><div class="muted">Net income: '+peso(net)+'</div></div></div>';drawOpexDetails(opexEntries);
  }
  function escapeHtml(text){return String(text||'').replace(/[&<>"']/g,function(char){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]})}
  function drawSalesReport(){var box=document.getElementById('salesReport');if(!box||!ready)return;var current=selected(),rows=invoices.filter(function(item){return period(item,current.month,current.year)&&number(item.amount_paid)>0});box.innerHTML=rows.length?'<div style="overflow:auto"><table><thead><tr><th>Invoice</th><th>Client / vehicle</th><th>Date</th><th>Received</th><th>Balance</th><th>Action</th></tr></thead><tbody>'+rows.map(function(item){var balance=Math.max(0,number(item.total_amount)-number(item.amount_paid));return '<tr><td><b>INV-'+String(item.invoice_number).padStart(5,'0')+'</b></td><td>'+escapeHtml(item.client_name)+'<br><small>'+escapeHtml(item.vehicle_make+' '+item.plate_number)+'</small></td><td>'+escapeHtml(item.invoice_date)+'</td><td><b>'+peso(item.amount_paid)+'</b></td><td>'+peso(balance)+'</td><td><button type="button" class="secondary" data-delete-sales-invoice="'+escapeHtml(item.id)+'">Delete</button></td></tr>'}).join('')+'</tbody></table></div>':'<div class="empty">No invoice payments received in this period.</div>'}
  function render(){drawDashboard();drawCashBalances();drawSalesReport()}
  async function load(){if(!db||!businessId)return;var branchId=localStorage.getItem('bwc-active-branch'),invoiceQuery=db.from('invoices').select('id,invoice_number,client_name,vehicle_make,plate_number,invoice_date,total_amount,amount_paid,invoice_services(service_name,amount)').eq('business_id',businessId),expenseQuery=db.from('expenses').select('expense_date,supplier_name,description,category,quantity,unit_amount,payment_method').eq('business_id',businessId),cashQuery=db.from('cash_transactions').select('cash_account,direction,amount').eq('business_id',businessId);if(branchId){invoiceQuery=invoiceQuery.eq('branch_id',branchId);expenseQuery=expenseQuery.eq('branch_id',branchId);cashQuery=cashQuery.eq('branch_id',branchId)}var data=await Promise.all([invoiceQuery.order('invoice_date',{ascending:false}),expenseQuery.order('expense_date',{ascending:false}),cashQuery]);if(data[0].error||data[1].error)return;invoices=data[0].data||[];expenses=data[1].data||[];cashRows=data[2].error?[]:(data[2].data||[]);ready=true;render()}
  function schedule(remote){clearTimeout(timer);timer=setTimeout(function(){remote?load():render()},80)}
  async function deleteInvoice(id){var branchId=localStorage.getItem('bwc-active-branch');if(!id||!confirm('Delete this invoice from Sales Report? This permanently removes the invoice, its services and parts, and its related cash-remittance record from this branch.'))return;var query=db.from('invoices').delete().eq('id',id).eq('business_id',businessId);if(branchId)query=query.eq('branch_id',branchId);var result=await query;if(result.error){alert('The sales record could not be deleted: '+result.error.message);return;}await load();document.dispatchEvent(new Event('bwc:invoice-deleted'));alert('Invoice deleted. Sales Report, Dashboard, Client Masterlist, and cash records were updated.');}
  async function start(){var config=window.BUSINESS_WEB_CENTER_SUPABASE||{};if(!window.supabase||!config.url||!config.publishableKey){setTimeout(start,300);return}db=window.businessSupabase||window.supabase.createClient(config.url,config.publishableKey);var session=await db.auth.getSession();if(!(session.data&&session.data.session))return;businessId=activeBusiness();if(!businessId)return;await load();document.addEventListener('bwc:invoices-loaded',function(){schedule(true)});document.addEventListener('bwc:expenses-loaded',function(){schedule(true)});document.addEventListener('bwc:cash-updated',function(){schedule(true)});document.addEventListener('click',function(event){var deletion=event.target.closest('[data-delete-sales-invoice]');if(deletion){deleteInvoice(deletion.dataset.deleteSalesInvoice);return;}if(event.target.closest('[data-t="dashboard"],[data-t="reports"],#scheduleTab'))schedule(false);if(event.target.closest('[onclick*="createInvoice"],[data-receipt-save],[data-exp-add]'))schedule(true)});document.addEventListener('change',function(event){if(['dm','dy'].includes(event.target.id))schedule(false)})}
  document.addEventListener('bwc:branch-ready',function(){cashRows=[];drawCashBalances();if(businessId)load()});
  setTimeout(start,900);
})();
