/* Online reporting layer. Dashboard and Sales Report use the same secure
   Invoice and Expense records as the rest of the business workspace. */
(function(){
  var db=null,businessId='',invoices=[],expenses=[],ready=false,timer=0;
  function peso(value){return 'PHP '+(Number(value||0)).toLocaleString('en-PH',{minimumFractionDigits:2,maximumFractionDigits:2})}
  function number(value){return Number(value||0)||0}
  function period(item,month,year){var date=new Date((item.invoice_date||item.expense_date||item.date)+'T00:00:00');return(!month||date.getMonth()===Number(month))&&(!year||String(date.getFullYear())===String(year))}
  function activeBusiness(){return localStorage.getItem('bwc-active-business')||''}
  function setText(id,value){var el=document.getElementById(id);if(el)el.textContent=value}
  function selected(){return {month:(document.getElementById('dm')||{}).value||'',year:(document.getElementById('dy')||{}).value||''}}
  function serviceSales(rows){var mix={};rows.forEach(function(invoice){var total=number(invoice.total_amount),paid=number(invoice.amount_paid),ratio=total?Math.min(1,paid/total):0;(invoice.invoice_services||[]).forEach(function(line){var name=line.service_name||'Service';mix[name]=(mix[name]||0)+number(line.amount)*ratio})});return mix}
  function drawDashboard(){if(!ready)return;var current=selected(),list=invoices.filter(function(item){return period(item,current.month,current.year)}),costItems=expenses.filter(function(item){return period(item,current.month,current.year)}),paid=list.filter(function(item){return number(item.amount_paid)>0}),sales=paid.reduce(function(sum,item){return sum+number(item.amount_paid)},0),unpaid=list.reduce(function(sum,item){return sum+Math.max(0,number(item.total_amount)-number(item.amount_paid))},0),cost=costItems.filter(function(item){return item.category==='Cost of Sales'}).reduce(function(sum,item){return sum+number(item.quantity)*number(item.unit_amount)},0),opex=costItems.filter(function(item){return item.category!=='Cost of Sales'}).reduce(function(sum,item){return sum+number(item.quantity)*number(item.unit_amount)},0),gross=sales-cost,net=gross-opex,mix=serviceSales(paid);
    setText('paidSales',peso(sales));setText('paidCount',paid.length+' invoice'+(paid.length===1?'':'s')+' with payment');setText('unpaid',peso(unpaid));setText('profit',peso(net));setText('gross',peso(gross));setText('net',peso(net));
    var expenseCard=document.querySelector('#dashboard .grid .card:nth-child(2) .metric');if(expenseCard)expenseCard.textContent=peso(opex);
    var expenseNote=document.querySelector('#dashboard .grid .card:nth-child(2) .muted:last-child');if(expenseNote)expenseNote.textContent=costItems.filter(function(item){return item.category!=='Cost of Sales'}).length+' OPEX entries';
    var serviceRows=Object.keys(mix).map(function(name){return '<div class="line"><span>'+escapeHtml(name)+'</span><b>'+peso(mix[name])+'</b></div>'}).join('')||'<div class="empty">No invoice payments received yet.</div>';
    var dashboardServices=document.getElementById('dashboardServices'),mixBox=document.getElementById('mix');if(dashboardServices)dashboardServices.innerHTML=serviceRows;if(mixBox)mixBox.innerHTML=serviceRows;
    var summary=document.getElementById('accountingSummaryCard');if(summary)summary.innerHTML='<div class="k">Accounting summary</div><h2>Sales, cost of sales, and OPEX</h2><div class="pl"><div><div class="k">Cash received</div><div class="metric">'+peso(sales)+'</div></div><div><div class="k">Cost of sales</div><div class="metric">'+peso(cost)+'</div><div class="muted">Gross profit: '+peso(gross)+'</div></div><div><div class="k">Total OPEX</div><div class="metric">'+peso(opex)+'</div><div class="muted">Net income: '+peso(net)+'</div></div></div>';
  }
  function escapeHtml(text){return String(text||'').replace(/[&<>"']/g,function(char){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]})}
  function drawSalesReport(){var box=document.getElementById('salesReport');if(!box||!ready)return;var current=selected(),rows=invoices.filter(function(item){return period(item,current.month,current.year)&&number(item.amount_paid)>0});box.innerHTML=rows.length?'<div style="overflow:auto"><table><thead><tr><th>Invoice</th><th>Client / vehicle</th><th>Date</th><th>Received</th><th>Balance</th></tr></thead><tbody>'+rows.map(function(item){var balance=Math.max(0,number(item.total_amount)-number(item.amount_paid));return '<tr><td><b>INV-'+String(item.invoice_number).padStart(5,'0')+'</b></td><td>'+escapeHtml(item.client_name)+'<br><small>'+escapeHtml(item.vehicle_make+' '+item.plate_number)+'</small></td><td>'+escapeHtml(item.invoice_date)+'</td><td><b>'+peso(item.amount_paid)+'</b></td><td>'+peso(balance)+'</td></tr>'}).join('')+'</tbody></table></div>':'<div class="empty">No invoice payments received in this period.</div>'}
  function render(){drawDashboard();drawSalesReport()}
  async function load(){if(!db||!businessId)return;var branchId=localStorage.getItem('bwc-active-branch'),invoiceQuery=db.from('invoices').select('invoice_number,client_name,vehicle_make,plate_number,invoice_date,total_amount,amount_paid,invoice_services(service_name,amount)').eq('business_id',businessId),expenseQuery=db.from('expenses').select('expense_date,category,quantity,unit_amount').eq('business_id',businessId);if(branchId){invoiceQuery=invoiceQuery.eq('branch_id',branchId);expenseQuery=expenseQuery.eq('branch_id',branchId)}var data=await Promise.all([invoiceQuery.order('invoice_date',{ascending:false}),expenseQuery.order('expense_date',{ascending:false})]);if(data[0].error||data[1].error)return;invoices=data[0].data||[];expenses=data[1].data||[];ready=true;render()}
  function schedule(remote){clearTimeout(timer);timer=setTimeout(function(){remote?load():render()},80)}
  async function start(){var config=window.BUSINESS_WEB_CENTER_SUPABASE||{};if(!window.supabase||!config.url||!config.publishableKey){setTimeout(start,300);return}db=window.businessSupabase||window.supabase.createClient(config.url,config.publishableKey);var session=await db.auth.getSession();if(!(session.data&&session.data.session))return;businessId=activeBusiness();if(!businessId)return;await load();document.addEventListener('bwc:invoices-loaded',function(){schedule(true)});document.addEventListener('bwc:expenses-loaded',function(){schedule(true)});document.addEventListener('click',function(event){if(event.target.closest('[data-t="dashboard"],[data-t="reports"],#scheduleTab'))schedule(false);if(event.target.closest('[onclick*="createInvoice"],[data-receipt-save],[data-exp-add]'))schedule(true)});document.addEventListener('change',function(event){if(['dm','dy'].includes(event.target.id))schedule(false)})}
  setTimeout(start,900);
})();
