/* Separate team accounts for the active business. No passwords are shared. */
(function(){
  var config=window.BUSINESS_WEB_CENTER_SUPABASE||{},db=null;
  function esc(s){return String(s||'').replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
  function moneyRole(role){return role==='owner'?'Owner':role==='admin'?'Admin':'Staff'}
  function addEntry(){var menu=document.getElementById('settingsMenu');if(!menu||document.getElementById('teamAccessMenuButton'))return;var b=document.createElement('button');b.id='teamAccessMenuButton';b.type='button';b.textContent='Team access';b.onclick=open;menu.appendChild(b)}
  async function ready(){if(db)return true;if(!window.supabase||!config.url||!config.publishableKey)return false;db=window.businessSupabase||window.supabase.createClient(config.url,config.publishableKey);return true}
  async function open(){document.getElementById('settingsMenu').classList.remove('open');if(!await ready())return alert('Online accounts are not connected yet.');var businessId=localStorage.getItem('bwc-active-business');var session=await db.auth.getSession(),user=session.data&&session.data.session&&session.data.session.user;if(!businessId||!user)return alert('Please sign in again first.');var mine=await db.from('business_memberships').select('role,status').eq('business_id',businessId).eq('user_id',user.id).maybeSingle();if(mine.error||!mine.data||mine.data.status!=='active'||!['owner','admin'].includes(mine.data.role))return alert('Only the business owner or an admin can manage team access.');var old=document.getElementById('teamAccessModal');if(old)old.remove();var modal=document.createElement('div');modal.id='teamAccessModal';modal.style.cssText='position:fixed;inset:0;background:#0008;z-index:120;display:grid;place-items:center;padding:18px';modal.innerHTML='<div class="card" style="width:min(100%,760px);max-height:90vh;overflow:auto"><div class="heading"><div><div class="k">Team access</div><h2>Separate accounts for your team</h2><p class="muted">Invite each person by email. They create their own password and see only this business workspace.</p></div><button class="secondary" type="button" data-team-close>Close</button></div><div class="notice">After inviting someone, tell them to open the Sign in page, choose <b>Create account</b>, select <b>Joining an existing team</b>, and use this same email address.</div><form id="teamInviteForm" class="formgrid" style="margin-top:14px"><label>Team member name<input id="teamInviteName" placeholder="e.g., Maria Santos"></label><label>Email address<input id="teamInviteEmail" type="email" required placeholder="maria@business.com"></label><label>Access role<select id="teamInviteRole"><option value="admin">Admin — can add and edit records</option><option value="staff">Staff — can view records</option></select></label><div class="actions" style="align-self:end"><button class="primary" type="submit">Invite team member</button></div></form><p class="muted" id="teamAccessMessage"></p><div class="k" style="margin-top:16px">Current team</div><div id="teamAccessList" class="empty">Loading team members…</div></div>';document.body.appendChild(modal);modal.addEventListener('click',function(e){if(e.target===modal||e.target.closest('[data-team-close]'))modal.remove()});document.getElementById('teamInviteForm').onsubmit=function(e){e.preventDefault();invite(businessId,user.id)};await draw(businessId)}
  async function draw(businessId){var target=document.getElementById('teamAccessList');if(!target)return;var result=await db.from('business_memberships').select('business_id,user_id,role,status,created_at,profiles(full_name,email)').eq('business_id',businessId).order('created_at');if(result.error){target.className='empty';target.textContent=result.error.message;return}var rows=result.data||[];target.className='';target.innerHTML=rows.length?'<div style="overflow:auto"><table><thead><tr><th>Team member</th><th>Email</th><th>Role</th><th>Status</th><th>Action</th></tr></thead><tbody>'+rows.map(function(r){var p=r.profiles||{},locked=r.role==='owner';return '<tr><td>'+esc(p.full_name||'Team member')+'</td><td>'+esc(p.email||'—')+'</td><td>'+moneyRole(r.role)+'</td><td>'+esc(r.status)+'</td><td>'+ (locked?'Owner account':'<button class="secondary" type="button" data-team-toggle="'+esc(r.user_id)+'" data-team-status="'+esc(r.status)+'">'+(r.status==='active'?'Deactivate':'Restore')+'</button>')+'</td></tr>'}).join('')+'</tbody></table></div>':'<div class="empty">No team members yet.</div>';target.querySelectorAll('[data-team-toggle]').forEach(function(b){b.onclick=function(){toggle(businessId,b.dataset.teamToggle,b.dataset.teamStatus==='active'?'inactive':'active')}})}
  async function invite(businessId,userId){var msg=document.getElementById('teamAccessMessage'),email=document.getElementById('teamInviteEmail').value.trim().toLowerCase(),name=document.getElementById('teamInviteName').value.trim(),role=document.getElementById('teamInviteRole').value;if(!email)return;msg.textContent='Saving invitation…';var result=await db.from('business_team_invites').upsert({business_id:businessId,email:email,full_name:name,role:role,status:'pending',invited_by:userId},{onConflict:'business_id,email'});if(result.error){msg.textContent=result.error.message;return}document.getElementById('teamInviteForm').reset();msg.textContent='Invitation saved. Ask '+email+' to create their own account using that email.';await draw(businessId)}
  async function toggle(businessId,userId,status){var msg=document.getElementById('teamAccessMessage');msg.textContent='Updating access…';var result=await db.from('business_memberships').update({status:status}).eq('business_id',businessId).eq('user_id',userId);msg.textContent=result.error?result.error.message:(status==='active'?'Access restored.':'Access removed.');if(!result.error)await draw(businessId)}
  addEntry();window.addEventListener('load',addEntry);
})();
